replicaCount: 1

app:
  name: postgres-test-app
  image:
    repository: asia-southeast1-docker.pkg.dev/new-devopts-k2-advance/app-repo/postgres-test-app
    tag: latest
    pullPolicy: Always
  containerPort: 3000
  livenessProbe:
    path: /
    port: 3000
    initialDelaySeconds: 45
    periodSeconds: 10

cloudSqlProxy:
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: "1.37.10"
  projectId: new-devopts-k2-advance
  region: asia-southeast1
  instanceName: dev-pg
  resources:
    limits:
      cpu: 100m
      memory: 128Mi

serviceAccountName: dev-pg-ksa

service:
  name: postgres-test-app-service
  type: LoadBalancer
  port: 80
