---
- name: Ensure Terraform is installed
  ansible.builtin.command: terraform version
  register: terraform_version
  changed_when: false

- name: Terraform Apply
  community.general.terraform:
    project_path: "{{ terraform_project_path }}"
    state: present
    force_init: true
  register: tf_apply

- name: Get Terraform outputs
  ansible.builtin.command: terraform output -json
  args:
    chdir: "{{ terraform_project_path }}"
  register: tf_outputs_json
  changed_when: false

- name: Parse Terraform outputs
  set_fact:
    tf_outputs: "{{ tf_outputs_json.stdout | from_json }}"