replicaCount: 1

app:
  name: chatbot-app
  image:
    repository: asia-southeast1-docker.pkg.dev/striking-figure-474817-a3/team1-ai-repo/chatbot-app
    tag: latest
    pullPolicy: Always
  containerPort: 3000
  livenessProbe:
    path: /
    port: 3000
    initialDelaySeconds: 45
    periodSeconds: 10

cloudSqlProxy:
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: "1.37.10"
  projectId: striking-figure-474817-a3
  region: asia-southeast1
  instanceName: instance-dev
  resources:
    limits:
      cpu: 100m
      memory: 128Mi

serviceAccountName: instance-dev-ksa

service:
  name: chatbot-app-service
  type: LoadBalancer
  port: 80
