apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test-app
  labels:
    app: postgres-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test-app
  template:
    metadata:
      labels:
        app: postgres-test-app
    spec:
      serviceAccountName: instance-dev-app-ksa
      containers:
        - name: postgres-test-app
          image: asia-southeast1-docker.pkg.dev/striking-figure-474817-a3/team1-ai-repo/postgres-test-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Cloud SQL Proxy to be ready..."
              # Chờ cho đến khi proxy sẵn sàng trên cổng 9090
              until wget -q -O /dev/null --tries=1 --timeout=1 http://127.0.0.1:9090/readiness; do
                echo "Proxy not ready, sleeping 1s..."
                sleep 1
              done
              
              echo "Proxy is ready, starting application."
              node app.js
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "127.0.0.1" # Cloud SQL private IP
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "num1-database"
            - name: DB_USER
              value: "num1-user"
            - name: DB_PASSWORD
              value: "Abc@12345678"
            - name: DB_SSL_MODE
              value: "disable"
            - name: GCS_BUCKET_NAME
              value: "app-bucket-dev-striking-figure-474817-a3"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
        
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
          args:
            - "striking-figure-474817-a3:asia-southeast1:instance-dev" # fix follow the Instance connection name
            - "--port=5432"
            - "--private-ip"
            - "--health-check"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-test-app-service
spec:
  selector:
    app: postgres-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
