apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test-app
  labels:
    app: postgres-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test-app
  template:
    metadata:
      labels:
        app: postgres-test-app
    spec:
      serviceAccountName: dev-pg-ksa
      containers:
        - name: postgres-test-app
          image: asia-southeast1-docker.pkg.dev/new-devopts-k2-advance/app-repo/postgres-test-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.37.10
          command:
            - "/cloud_sql_proxy"
            - "-instances=new-devopts-k2-advance:asia-southeast1:dev-pg=tcp:5432"
            - "-enable_iam_login"
          env:
            - name: PROJECT_ID
              value: "new-devopts-k2-advance"
            - name: REGION
              value: "asia-southeast1"
            - name: INSTANCE_NAME
              value: "dev-pg"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-test-app-service
spec:
  selector:
    app: postgres-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
