apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "50Gi" }}