# Kubernetes Config
kubeconfig_path: "~/.kube/config"
namespace: "default"
environment: "dev"

# Ray / AI Configuration
ray_cluster_name: "ray-cluster"
ai_service_name: "qwen-unified-service" # Tên service K8s của con AI
ai_service_port: 8000

# Image Names (Đặt tên để Cloud Build tạo ra)
ai_image_name: "qwen2-serve"
ai_image_tag: "v1"

# Terraform Paths
terraform_project_path: "{{ playbook_dir }}/../environments/dev"

# Paths Source Code
ai_source_path: "{{ playbook_dir }}/../ai-model" # Đường dẫn code App


# Timeout Deployment
wait_timeout: 300